
// default package
// Generated 20.Þub.2023 23:13:31 by Hibernate Tools 5.2.12.Final

/**
 * Accountt generated by hbm2java
 */
public class Accountt implements java.io.Serializable {

	private String id;
	private Customerr customerr;
	private String iban;
	private String balance;
	private String latestTransaction;
	private String lastWrongLogin;

	public Accountt() {
	}

	public Accountt(String id) {
		this.id = id;
	}

	public Accountt(String id, Customerr customerr, String iban, String balance, String latestTransaction,
			String lastWrongLogin) {
		this.id = id;
		this.customerr = customerr;
		this.iban = iban;
		this.balance = balance;
		this.latestTransaction = latestTransaction;
		this.lastWrongLogin = lastWrongLogin;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Customerr getCustomerr() {
		return this.customerr;
	}

	public void setCustomerr(Customerr customerr) {
		this.customerr = customerr;
	}

	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public String getBalance() {
		return this.balance;
	}

	public void setBalance(String balance) {
		this.balance = balance;
	}

	public String getLatestTransaction() {
		return this.latestTransaction;
	}

	public void setLatestTransaction(String latestTransaction) {
		this.latestTransaction = latestTransaction;
	}

	public String getLastWrongLogin() {
		return this.lastWrongLogin;
	}

	public void setLastWrongLogin(String lastWrongLogin) {
		this.lastWrongLogin = lastWrongLogin;
	}

}
