

/**
 * AddresssId generated by hbm2java
 */
public class AddresssId implements java.io.Serializable {

	private String id;
	private String country;
	private String city;
	private String postCode;
	private String customer›d;

	public AddresssId() {
	}

	public AddresssId(String id) {
		this.id = id;
	}

	public AddresssId(String id, String country, String city, String postCode, String customer›d) {
		this.id = id;
		this.country = country;
		this.city = city;
		this.postCode = postCode;
		this.customer›d = customer›d;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getCustomer›d() {
		return this.customer›d;
	}

	public void setCustomer›d(String customer›d) {
		this.customer›d = customer›d;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddresssId))
			return false;
		AddresssId castOther = (AddresssId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getPostCode() == castOther.getPostCode()) || (this.getPostCode() != null
						&& castOther.getPostCode() != null && this.getPostCode().equals(castOther.getPostCode())))
				&& ((this.getCustomer›d() == castOther.getCustomer›d())
						|| (this.getCustomer›d() != null && castOther.getCustomer›d() != null
								&& this.getCustomer›d().equals(castOther.getCustomer›d())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getPostCode() == null ? 0 : this.getPostCode().hashCode());
		result = 37 * result + (getCustomer›d() == null ? 0 : this.getCustomer›d().hashCode());
		return result;
	}

}
