
// default package
// Generated 20.Şub.2023 23:13:31 by Hibernate Tools 5.2.12.Final

/**
 * Addresss generated by hbm2java
 */
public class Addresss implements java.io.Serializable {

	private AddresssId id;
	private Customerr customerr;

	public Addresss() {
	}

	public Addresss(AddresssId id) {
		this.id = id;
	}

	public Addresss(AddresssId id, Customerr customerr) {
		this.id = id;
		this.customerr = customerr;
	}

	public AddresssId getId() {
		return this.id;
	}

	public void setId(AddresssId id) {
		this.id = id;
	}

	public Customerr getCustomerr() {
		return this.customerr;
	}

	public void setCustomerr(Customerr customerr) {
		this.customerr = customerr;
	}

}
