// default package
// Generated 20.Þub.2023 23:13:31 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Customerr generated by hbm2java
 */
public class Customerr implements java.io.Serializable {

	private String id;
	private String name;
	private String surname;
	private String email;
	private String phone;
	private Set accountts = new HashSet(0);
	private Set addressses = new HashSet(0);
	private Set phonees = new HashSet(0);

	public Customerr() {
	}

	public Customerr(String id) {
		this.id = id;
	}

	public Customerr(String id, String name, String surname, String email, String phone, Set accountts, Set addressses,
			Set phonees) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.phone = phone;
		this.accountts = accountts;
		this.addressses = addressses;
		this.phonees = phonees;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getAccountts() {
		return this.accountts;
	}

	public void setAccountts(Set accountts) {
		this.accountts = accountts;
	}

	public Set getAddressses() {
		return this.addressses;
	}

	public void setAddressses(Set addressses) {
		this.addressses = addressses;
	}

	public Set getPhonees() {
		return this.phonees;
	}

	public void setPhonees(Set phonees) {
		this.phonees = phonees;
	}

}
