// default package
// Generated 20.Þub.2023 23:13:31 by Hibernate Tools 5.2.12.Final

/**
 * Phonee generated by hbm2java
 */
public class Phonee implements java.io.Serializable {

	private String id;
	private Customerr customerr;
	private String phoneime;
	private String number;

	public Phonee() {
	}

	public Phonee(String id) {
		this.id = id;
	}

	public Phonee(String id, Customerr customerr, String phoneime, String number) {
		this.id = id;
		this.customerr = customerr;
		this.phoneime = phoneime;
		this.number = number;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Customerr getCustomerr() {
		return this.customerr;
	}

	public void setCustomerr(Customerr customerr) {
		this.customerr = customerr;
	}

	public String getPhoneime() {
		return this.phoneime;
	}

	public void setPhoneime(String phoneime) {
		this.phoneime = phoneime;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

}
